add channel support to install action
rancher/elemental-cli pull request #132
Opened 2022-03-09 13:40 UTC by Itxaka

Partially fixes https://github.com/rancher-sandbox/cOS-toolkit/issues/1160

Cant be this easy...can it?

Signed-off-by: Itxaka <igarcia@suse.com>

2022-03-09 15:03 UTC, davidcassany reviewed
Oh, is this that easy? If so please add it to `reset` command too :) Looks really good

What is unclear to me is from where it comes the `config.ChannelUpgrades` value. Basically this is the main reason I did not implement it at a time. Since the behavior was not clear to me and I did not want to add too many features on a single PR.

My question is, if we run `elemental install /dev/sda`  what is the value of `confing.ChannelUpgrades`, if `true` it means it will not attempt to install from the installation media. Probably we can do something smarter.

2022-03-09 15:03 UTC, davidcassany commented on pkg/action/install.go
> +		activeImg.Source = v1.NewChannelSrc(cnst.ChannelSource)
I am not sure how ChannelUggrades is set by default. But to me this looks a bit tricky as there is no flag for it. I suggest to give priority to the installation from `cnst.IsoBaseTree` (aka the installation media). So what about the following:

```golang
} else if exists, _ := afero.Exists(u.Config.Fs, cnst.IsoBaseTree); exists {
    activeImg.Source = v1.NewDirSrc(cnst.IsoBaseTree)
} else if config.ChannelUpgrades {
    activeImg.Source = v1.NewChannelSrc(cnst.ChannelSource)
} else {
    return errors.New("No installation media defined")
}
```

This way running `elemental install /dev/sda` forma  device media will install whatever is in the ISO and `elemental install /dev/loop0` (not running from an ISO) will install latest `system/cos` from the channel.

The the exact same change could be applied to the `reset` command and we are done :)

2022-03-09 15:11 UTC, Itxaka commented on pkg/action/install.go
> +		activeImg.Source = v1.NewChannelSrc(cnst.ChannelSource)
:+1: I had that same question when adding it, what would go first.

2022-03-09 15:22 UTC, Itxaka commented
> What is unclear to me is from where it comes the config.ChannelUpgrades value. Basically this is the main reason I did not implement it at a time. Since the behavior was not clear to me and I did not want to add too many features on a single PR.

So this comes from loading the default config files from cos: https://github.com/rancher-sandbox/elemental/blob/main/cmd/config/config.go#L100 which loads `/etc/cos-upgrade-image` which usually has the CHANNEL_UPGRADES and the UPGRADE_IMAGE vars, which is why on a running system the channel upgrades should always be the last one/fallback if nothing specified.

In the current case, we would need to identify if we are running from iso or `cnst.IsoBaseTree` exists before falling back to channel upgrades as otherwise from iso/recovery/running system there is always gonna be a  `/etc/cos-upgrade-image`  which those values

2022-03-09 15:33 UTC, davidcassany commented on pkg/action/install.go
> +		activeImg.Source = v1.NewChannelSrc(cnst.ChannelSource)
> The the exact same change could be applied to the `reset` command and we are done :)

@Itxaka after thinking about it twice I think that better forget about  `reset` command. Channel source doesn't make much sense there and the expected behavior is not that simple, as in `reset` command there will always be the default source dir available, hence the upgrades from channel should be an opt in for that case. Probably better leave it for now.

2022-03-10 08:30 UTC, mudler approved these changes
looks good!

2022-03-10 10:19 UTC, davidcassany requested changes

2022-03-10 10:19 UTC, davidcassany commented on pkg/action/install.go
> +		// If cnst.IsoBaseTree exists we are booting from iso, use that as source
nit: can't it be a plain sequence of `else if`? I don't see the difference with nested ifs. just a matter of style, as you wish.

2022-03-10 10:19 UTC, davidcassany commented on pkg/action/install.go
> +	if activeImg.Source.Value() == "" {
This will fail on `--iso`, if you use this flag from a non installation media and without channel upgrades on Souce will be empty. Probably we can make iso with the highest priority, in fact `--iso`, `--docker-image` and `--directory` should not be used together.

2022-03-10 10:19 UTC, davidcassany commented on pkg/action/install.go
>  	if config.DockerImg != "" {
```suggestion
	if config.Iso != "" {
		activeImg.Source = v1.NewDirSrc("downloadedISO")
	} else if config.DockerImg != "" {
```

2022-03-10 10:19 UTC, davidcassany commented on pkg/action/install.go
> +	if activeImg.Source.Value() == "" {
Probably we can make sources of the downloaded ISO predictable, so mount the downloaded ISO into some constant paths so we can set the Source here and forget about it. The current impletmentation of GetISO downloads the ISO into tmp folder and mounts it there and sets the Sources for active and recovery acording to the temporary path.

But I would leave this to a follow up PR.

2022-03-10 10:31 UTC, Itxaka commented on pkg/action/install.go
>  	if config.DockerImg != "" {
umm, but this is a new thingie, isnt it? I dont mind adding it tot he PR but maybe it gets more complicated that expected and should be properly tracked. Do we have a card for this already?

2022-03-10 10:32 UTC, Itxaka commented on pkg/action/install.go
> +		// If cnst.IsoBaseTree exists we are booting from iso, use that as source
sure, I just find nested if more readable (I know, I know, should be the other way `¯\_(ツ)_/¯`)

2022-03-10 10:33 UTC, Itxaka commented on pkg/action/install.go
>  	if config.DockerImg != "" {
ah I see, this complements the comment below about the --iso

2022-03-10 10:36 UTC, davidcassany commented on pkg/action/install.go
>  	if config.DockerImg != "" {
No, is is not new, it is parsed during the install. `elemental.GetIso()` method gets called based on `config.Iso != ""` and downloads the ISO, mounts the ISO and then sets activeImg and recoveryImg to the proper sources. Yes, I dislike this approach of setting it dynamically after downloading, but this can be fixed in another PR. The problem with the current PR is that we can hit the empty Source error if we use the `--iso` flag, which is currently supported.

2022-03-10 10:40 UTC, Itxaka commented on pkg/action/install.go
> +	if activeImg.Source.Value() == "" {
is there anything that prevents use from downloading the iso during the installsetup?

2022-03-10 10:49 UTC, Itxaka commented on pkg/action/install.go
> +	if activeImg.Source.Value() == "" && config.Iso == "" {
cc @davidcassany

2022-03-10 10:50 UTC, davidcassany commented on pkg/action/install.go
> +	if activeImg.Source.Value() == "" && config.Iso == "" {
Yes that's also a good option

2022-03-10 10:54 UTC, davidcassany commented on pkg/action/install.go
> +	if activeImg.Source.Value() == "" {
I guess we could consider it but this is a bigger change and makes the iso download happen before the `before-install` hook (though I don't think we should care about it).

Also I like this setup methods to be super light, this is good for testing and from an API PoV.

2022-03-10 10:55 UTC, davidcassany approved these changes

2022-03-10 12:32 UTC, davidcassany commented
@Itxaka the grubtest test fails because now `InstallImagesSetup` method does not have default Source for ActiveImage, it can error out depending on the host and configs context, I guess for this test there is no source defined.

2022-03-10 12:33 UTC, Itxaka commented
Yep, good eye @davidcassany. I have fixed the other tests but failed to catch this one :)

2022-03-10 13:00 UTC, merged