Try to use container image from local cache first
rancher/elemental-cli pull request #185
Opened 2022-05-09 08:46 UTC by mjura

We want to use container image from local cache first as default,
if image is not present in local cache then try to download and
extract it from remote.

Fixes #1279

Signed-off-by: Michal Jura <mjura@suse.com>

2022-05-09 13:33 UTC, mudler commented on pkg/luet/luet.go
> +		l.log.Infof("An image does not exist locally, pulling from remote")
I'm not completely sure about this, failing back looks good but it might not be always what we want. Let's suppose I'm iterating locally against a tag which was already published and accidentally I remove it from docker, It would go straight building and I would not be able to notice that I'm building an image that I did not want to.

2022-05-09 13:34 UTC, mudler commented on pkg/luet/luet.go
> +		l.log.Infof("An image does not exist locally, pulling from remote")
maybe instead of taking a `local` flag, should it take a `localOnly` boolean?

2022-05-09 13:35 UTC, Itxaka commented on pkg/luet/luet.go
> +			l.log.Infof("Size: %s", units.BytesSize(float64(info.Target.Size)))
Should probably log here that we found the image locally just in case.

2022-05-09 13:37 UTC, Itxaka commented on pkg/luet/luet.go
> +		l.log.Infof("An image does not exist locally, pulling from remote")
Agreed, this should be flag-able so users can control. I do think that making it the default might be good though

2022-05-09 13:38 UTC, Itxaka commented on pkg/elemental/elemental.go
> +		err = c.config.Luet.Unpack(img.MountPoint, img.Source.Value(), true)
umm, I wonder why this is not configurable and its hardcoded....

2022-05-09 13:45 UTC, mudler commented on pkg/elemental/elemental.go
> +		err = c.config.Luet.Unpack(img.MountPoint, img.Source.Value(), true)
yes, I wondered as well too. I think it is a side-effect of the fallback logic, it is always enabled as it tries local first.

2022-05-09 13:59 UTC, mjura commented on pkg/elemental/elemental.go
> +		err = c.config.Luet.Unpack(img.MountPoint, img.Source.Value(), true)
This is because `elemental install` doesn't support `--local` option, we can add it if you think that it is needed

2022-05-09 13:59 UTC, mjura commented on pkg/luet/luet.go
> +			l.log.Infof("Size: %s", units.BytesSize(float64(info.Target.Size)))
I have added information about it, thank you

2022-05-09 14:01 UTC, mjura commented on pkg/luet/luet.go
> +		l.log.Infof("An image does not exist locally, pulling from remote")
Following logic is the most natural for me:
1. To use image, check it in local cache first
2. If not present then try to pull it from remote

Additional flags will only confuse our users. But if you want to have flag `--local-only` or `--remote-only` we can add them

2022-05-09 14:05 UTC, mudler commented on pkg/luet/luet.go
> +		l.log.Infof("An image does not exist locally, pulling from remote")
the problem with this approach is that you don't guarantee anymore what is the result of your artifact unless you look up at the logs, so any call to the same command could potentially yields different results

2022-05-09 14:19 UTC, Itxaka commented on pkg/elemental/elemental.go
> +		err = c.config.Luet.Unpack(img.MountPoint, img.Source.Value(), true)
umm, Im not sure if that is good or not. I mean, it would work greatly for air-gapped system maybe? You could build an iso with all the images on a local docker registry and then install systems from there?

But I think thats out of scope of this card, I would leave it as is.

2022-05-10 05:09 UTC, mjura commented on pkg/luet/luet.go
> +		l.log.Infof("An image does not exist locally, pulling from remote")
After our discussion, current logic will be as follows:
1. To use image, check it in local cache first
2. If not present then try to pull it from remote
3. If --local-only option was set then don't use remote

2022-05-10 05:10 UTC, mjura commented on pkg/elemental/elemental.go
> +		err = c.config.Luet.Unpack(img.MountPoint, img.Source.Value(), true)
After changes, it will work for air-gapped environments, we have added --local-only option which will rely only on local cache.

2022-05-10 07:24 UTC, Itxaka approved these changes

2022-05-10 07:24 UTC, Itxaka commented on pkg/elemental/elemental.go
> +		err = c.config.Luet.Unpack(img.MountPoint, img.Source.Value(), true)
Awesome, but now I wonder if we want 2 different flags for this, like --local for try local then remote and --local-only for only try local.

Anyway, we can come back to this later to add that.

2022-05-10 10:09 UTC, mudler commented on pkg/elemental/elemental.go
> +		err = c.config.Luet.Unpack(img.MountPoint, img.Source.Value(), true)
This should be false by default in his case here, right? otherwise we would fail upgrading as we would always try from local cc: @Itxaka

2022-05-10 10:18 UTC, Itxaka commented on pkg/elemental/elemental.go
> +		err = c.config.Luet.Unpack(img.MountPoint, img.Source.Value(), true)
Not as far as Im understanding, this will try to get the image from local on upgrade, but would fail and try from remote. Of course this changes the behavior of anything that gets a docker image (install, upgrade, reset, pull-image I think?) so Im not sure about that.

2022-05-10 10:20 UTC, Itxaka commented on pkg/elemental/elemental.go
> +		err = c.config.Luet.Unpack(img.MountPoint, img.Source.Value(), true)
As we dropped using the real luet for upgrade tests, this path is not properly tested, we should probably try to test this further.

2022-05-10 10:27 UTC, mudler commented on pkg/elemental/elemental.go
> +		err = c.config.Luet.Unpack(img.MountPoint, img.Source.Value(), true)
ok, so yes, this needs to be properly instrumented otherwise hardcoded value here have a different meaning depending on what context this is being used on.

2022-05-10 10:28 UTC, mudler requested changes
`elemental.CopyImage` can't take an hardcoded value here, otherwise it will just work during building the iso, but it would fail during upgrades/install and all the other scenarios relying on `CopyImage`.

2022-05-10 11:12 UTC, mjura commented on pkg/elemental/elemental.go
> +		err = c.config.Luet.Unpack(img.MountPoint, img.Source.Value(), true)
ok, my idea would be then to add --local-only flag to elemental install, upgrade and build-iso and then reuse it in CopyImage function. What do you think ?

2022-05-10 11:27 UTC, Itxaka commented
Easy solution here would be to add a --local flag to all the commands using the unpack and pass that down to the unpacker

2022-05-10 12:00 UTC, mjura commented
Ok, let's add local flag to all the commands using the unpack and pass that down to the unpacker

2022-05-16 12:41 UTC, mudler approved these changes
Looks good here!

2022-05-17 15:11 UTC, merged