Copy ARM firmware files to boot partition
rancher/elemental-cli pull request #395
Opened 2022-12-14 18:24 UTC by kkaempf

Fixes #391

Signed-off-by: Klaus Kämpf <kkaempf@suse.de>

2022-12-16 08:35 UTC, davidcassany requested changes
I'd move the copy all files logic to an utility function to test it properly in unit tests. Then I'd also try to code a grub unit test covering this arm path.

@kkaempf let us know if you prefer to us to code such a little extension on top of your branch

2022-12-16 08:35 UTC, davidcassany commented on pkg/utils/grub.go
> +		// run via shell for "*" extension
@kkaempf thanks much for the fix.

I'd rather create an utility for copying all files in a folder (we could even include recursive flag). Probably it will be also be used in other places and it could be easily tested in unit tests.

2022-12-16 08:46 UTC, kkaempf commented
I'm a Go illiterate (I can copy & paste though 😝 ) and would very much prefer help here 😉

2022-12-16 13:38 UTC, davidcassany commented
Rebased and refactored to make use of new CopyDirectory utility method.

2022-12-16 13:52 UTC, davidcassany commented on pkg/utils/grub.go
> +const armFirmwarePath = "/boot/vc"
@kkaempf it is unclear where this path comes from. I doubt we can assume this is always valid, even in non SUSE systems. Gonna try to investigate it, but I am pretty ignorant on the device tree topic.

2022-12-16 13:54 UTC, davidcassany commented on pkg/utils/common.go
> +	return fs.Chmod(target, fInf.Mode())
I realized our former CopyFile method was not keeping former file mode, I think it is better to simply keep it, if this raises some issue we can later evolve it to apply custom file modes, but I'd rather keep it simple for now and see.

2022-12-16 14:23 UTC, kkaempf commented on pkg/utils/grub.go
> +const armFirmwarePath = "/boot/vc"
This path comes from the `raspberrypi-firmware*` rpms

2022-12-16 14:28 UTC, kkaempf reviewed
I'd happily give this a try at https://build.opensuse.org/package/show/home:kwk:osimage/elemental-cli 😉

2022-12-16 14:28 UTC, kkaempf commented on pkg/utils/common.go
> +func CopyDirectory(fsys v1.FS, srcDir, dstDir string) error {
Does this do a recursive copy ? It's not immediately obvious to me.

2022-12-16 16:02 UTC, davidcassany reviewed
I don't think this PR can be merged as is. Could be used for testing and validating the logic, but we should follow some other approach. Adding this patch in grub installation logic is RPI & openSUSE specific, we should avoid that.

2022-12-16 16:02 UTC, davidcassany commented on pkg/utils/common.go
> +func CopyDirectory(fsys v1.FS, srcDir, dstDir string) error {
Yes it does

2022-12-16 16:02 UTC, davidcassany commented on pkg/utils/common.go
> +	return WalkDirFs(fsys, srcDir, func(path string, d fs.DirEntry, err error) error {
This is the recursive method. `WalkDirFs` calls the function provided as a parameter to all files it finds in the tree.

2022-12-16 16:02 UTC, davidcassany commented on pkg/utils/grub.go
> +const armFirmwarePath = "/boot/vc"
Yes I realized that and I believe this is openSUSE & raspberry specific, hence I am not really in favor of adding this stuff here... See the arm openSUSE images built with KIWI, it is quite frustrating to see an if clause for each board where some firmware board specific magic is applied. Here is the [script](https://build.opensuse.org/package/view_file/openSUSE:Factory:ARM:ToTest/JeOS/uboot-image-raspberrypi-install?expand=1) that patches boot for a rpi (and others) image.

2022-12-16 16:02 UTC, davidcassany commented on pkg/utils/grub.go
> +const armFirmwarePath = "/boot/vc"
I believe this logic should be applied somewhere else, u-boot related stuff is board specific. A couple (or so) of years ago we declined adding some specific u-boot support to KIWI because is was just not possible to set something generic template that could be functional for `arm` in general.

2022-12-16 16:08 UTC, davidcassany commented
I believe the logic to add this firmware files in EFI partitions should somehow be part of https://build.opensuse.org/package/view_file/isv:Rancher:Elemental:Dev/elemental-post-build-generate-rpi-image/generate-rpi-image.sh?expand=1

2022-12-19 07:34 UTC, kkaempf commented on pkg/utils/grub.go
> +const armFirmwarePath = "/boot/vc"
I more and more believe we should differentiate between `architecture` (like ARM) and `platform` (like RPi) to cover all these variants.

2022-12-19 07:36 UTC, kkaempf commented on pkg/utils/grub.go
> +const armFirmwarePath = "/boot/vc"
That said, there's huge interest in Elemental + RPi from various sides.

Btw, this PR (plus fixing #393) makes Rancher+Elemental fully functional on Raspberry. 😉

2022-12-19 08:42 UTC, kkaempf commented
> I believe the logic to add this firmware files in EFI partitions should somehow be part of https://build.opensuse.org/package/view_file/isv:Rancher:Elemental:Dev/elemental-post-build-generate-rpi-image/generate-rpi-image.sh?expand=1

It's already there (otherwise the `.raw` image wouldn't even boot 😉 ) - for the ~installation~seed image.

This PR, however, is for the `elemental install` part.

2022-12-19 08:51 UTC, davidcassany commented on pkg/utils/grub.go
> +const armFirmwarePath = "/boot/vc"
> I more and more believe we should differentiate between `architecture` (like ARM) and `platform` (like RPi) to cover all these variants.

I definitely agree on that statement. However I am a bit resistant to start adding these variants in elemental-cli, it can easily grow into a monster.

What if we make the platform a user provided value? it could be a value in out elemental-cli config. So we do not have to code heuristics to determine the platform, we just assume we know which one is.

2022-12-19 09:01 UTC, davidcassany commented
> > I believe the logic to add this firmware files in EFI partitions should somehow be part of https://build.opensuse.org/package/view_file/isv:Rancher:Elemental:Dev/elemental-post-build-generate-rpi-image/generate-rpi-image.sh?expand=1
> 
> It's already there (otherwise the `.raw` image wouldn't even boot wink ) - for the ~installation~seed image.
> 
> This PR, however, is for the `elemental install` part.

Yes I know there is interest in RPi and it would be really  nice being capable to provide demos using RPi. I am really in to get this sorted out and provide a functional solution, I do have concerns about not approaching it as we should though. 

I am also wondering why are we considering an `elemental install` step for RPi if we are already building a disk image, there is already a detection `elemental register` command not to install a system over a previous installation. As far as I understand this requires a couple of block devices in RPi, one as the installation media and another one where to install the system. These two are removable devices, it feels odd to me. One should be enough.

Still thinking about this story...

2022-12-19 10:37 UTC, kkaempf commented on pkg/utils/grub.go
> +const armFirmwarePath = "/boot/vc"
I'd absolutely agree to that !

2022-12-20 08:35 UTC, davidcassany commented
For now I'd vote to manage this in an after-install hook. I created an elemental-cli PR to execute `after-install` hooks earlier, just right after `after-install-chroot`, this way both are applied in the same step with the only difference of being in a chroot or not, which is also what the name suggests. This allows to run after-install hooks while the OS image being deployed is loop mounted and all the relevant partitions are also mounted, all in rw mode.

https://github.com/rancher/elemental-cli/pull/399

With this change we can easily consider adding a simpler after-install hook to do the job within the installation media, see https://build.opensuse.org/package/show/home:dcassany:Elemental:Dev/elemental-post-build-generate-rpi-image

With this two changes set for registering a RPi it would be needed to reference the additional hook by adding a `config-urls` flag in registration yaml:

```yaml
    elemental:
      ...
      install:
        ...
        config-urls:
        - "/run/initramfs/live/01_rpi-install-hook.yaml"
```

Need validate this approach, but, for now, I think this should be the way to go and move use case specific logic to hooks.

2022-12-21 08:58 UTC, davidcassany commented
@kkaempf I am building a RPi image in https://build.opensuse.org/project/show/home:dcassany:Elemental:Dev:Teal53 that should be ready to be used. Do you think you can get it a trial? I'd be more in favor of using the hooks approach rather than coding it into the elemental-cli grub install.

Just need to make sure to include the `config-dir` within the registration yaml:

```yaml
...
install:
  config-dir: "/run/initramfs/live/elemental"
  ...
```

I wonder if it makes sense having this config dir as a default, so we can simply provide a custom `config.yaml` for elemental-cli by dropping it in `/elemental` on the ISO filesystem.

2022-12-21 11:44 UTC, davidcassany commented
Closing as this has been fixed by adding an after-install hook in installation media.

2022-12-21 11:44 UTC, closed without merging