Refactor elemental
rancher/elemental-cli pull request #404
Opened 2023-01-11 10:55 UTC by davidcassany

This commit refactors elemental image deploy procedure to always create and prepare the root tree in a temporary folder before synching it to a filesystem image most likely as a mounted loop device.

This change has a couple of immediate benefits:

1. We can pre-compute the root tree size before creating the filesystem  image. Hence image sizes can be adjusted to root-tree size.

2. There is no path differentiation between filesystems. The root tree is prepared following the same logic independently of the target filesystem. Squashfs is no longer an exception, building the image follows the same logic as it was any other writable filesystem.

We also can argue this is a simple, robust and flexible logic compared with the previous code.

The counter part is having to prepare the root-tree to later on copy it to the final image, this causes the root-tree to be written twice, one to prepare it and another one to sync it to the target location.

2023-01-12 08:12 UTC, kkaempf requested changes
I'd recommend to put the copyright year changes in a separate PR

2023-01-12 13:59 UTC, frelon commented on pkg/elemental/elemental.go
> +// CopyFileImg copies the files targed as the source of this image. It also applies the img label over the copied image.
Nit: targed

2023-01-13 14:41 UTC, frelon commented on pkg/utils/common.go
> +// 1st source name file. The result keeps the file mode of the 1st source.
Just curious, why only the 1st source?

2023-01-16 12:55 UTC, davidcassany commented on pkg/utils/common.go
> +// 1st source name file. The result keeps the file mode of the 1st source.
Yes I know this might look weird. This method concatenates several files, if only used with a single file this is a simple copy.

So imagine a call (pseudo code) like:

```
concat my/file1 my/file2 my/file3 my/folder/
```

The result will be a `my/folder/file1` with `file2` and `file3` appended to it. So permissions and file name are just borrowed from the first one. So if there is only a single file this is indeed a regular copy. If there was a nice way of adding a default file mode with some sort of optional argument this is what I'd have done.

2023-01-16 13:00 UTC, frelon commented on pkg/utils/common.go
> +// 1st source name file. The result keeps the file mode of the 1st source.
Aha, gotcha!

2023-01-16 13:24 UTC, kkaempf approved these changes
lgtm 🤞🏻

2023-01-16 13:51 UTC, frelon approved these changes
Works like a charm!

2023-01-16 16:52 UTC, fgiudici approved these changes

2023-01-17 08:56 UTC, merged