Add multi-arch support for pulling images
rancher/elemental-cli pull request #478
Opened 2023-04-24 09:21 UTC by frelon

This commit refactors the image pulling and extracting to be able to cross-build isos.

In order to do this we make use of go-containerregistry and containerd to pull and extract the image.

This refactor also removes alot of luet functionality mostly used for build-disk command which has been deprecated.

2023-04-24 10:16 UTC, davidcassany reviewed
Really interesting, nice job! I like it. We have to carefully consider this change as it affects in several places and drops some (unused) features. 

Out of curiosity? Have you compared the size of the out coming binary? I'd be curious to check of there is a significant change.

It is relevant to note this change incompatible with the current elemental-toolkit repository structure. It would require adopting the restructure from davidcassany/elemental-toolkit#3 and the first half of rancher/elemental-toolkit#1738

2023-04-24 10:16 UTC, davidcassany commented on pkg/types/v1/image.go
> +	ExtractImage(imageRef, destination, platformRef string, local bool) error
@frelon have you checked if the library easily supports pulling from a private registry. I guess it does. I'd say even if this is not coded now we should consider this use case and check no big API changes will be needed if such a feature is added later on.

2023-04-24 10:16 UTC, davidcassany commented on pkg/types/v1/common.go
> +func (i ImageSource) IsImage() bool {
I like the rename

2023-04-24 10:16 UTC, davidcassany commented on pkg/types/v1/image.go
> +		return daemon.Image(ref)
Do we know how this works? Does it support containerd? Would be really cool if that would also be functional for containerd too.

2023-04-24 10:16 UTC, davidcassany commented on tests/fixtures/config/config.yaml
> +    uri: docker:some/image:latest
`some/image:latest` should also be fine, as `docker:` or `oci:` type is the expected default.

2023-04-24 10:56 UTC, frelon commented
> Really interesting, nice job! I like it. We have to carefully consider this change as it affects in several places and drops some (unused) features.

Nice! Yep, it became bigger and bigger since the dropped dependencies used alot of old packages in turn. I will run more tests this week but an initial build and boot of elemental-teal was successful.

> Out of curiosity? Have you compared the size of the out coming binary? I'd be curious to check of there is a significant change.

I did a quick check and it seems we go from ~24MB to ~18MB.

> It is relevant to note this change incompatible with the current elemental-toolkit repository structure. It would require adopting the restructure from https://github.com/davidcassany/elemental-toolkit/pull/3 and the first half of https://github.com/rancher/elemental-toolkit/issues/1738

Hmm, I'm probably missing something but I think this change should be compatible with only some minor modifications to the toolkit?

2023-04-24 11:08 UTC, frelon commented on pkg/types/v1/image.go
> +		return daemon.Image(ref)
Hmm, it does not seem to support containerd out-of-the-box but might be able to just point it to the correct socket. The library also has abstracted this, so it's possible to write a custom client to fetch the image. I will experiment a bit with this!

2023-04-24 11:12 UTC, davidcassany commented
> Hmm, I'm probably missing something but I think this change should be compatible with only some minor modifications to the toolkit?

Well, depends on what minor means 😅 I bet the CI will have several breaks here and there with such a change included within toolkit, as the CI relies on channels in some places. And again, I don't think spending time to adapt the CI there makes much sense, better rearrange it not to be a Luet centric project first, then it should not much impact if any at all. You already know how maddening it can be the toolkit CI 😅

2023-04-24 11:12 UTC, frelon commented on pkg/types/v1/image.go
> +	ExtractImage(imageRef, destination, platformRef string, local bool) error
It's the same library as used before, but a newer version so it should be possible to pull from any registry. Will have to bring back the authentication though, as I ripped that out in the refactor. Will test that also!

2023-04-24 11:13 UTC, frelon commented
> > Hmm, I'm probably missing something but I think this change should be compatible with only some minor modifications to the toolkit?
> 
> Well, depends on what minor means sweat_smile I bet the CI will have several breaks here and there with such a change included within toolkit, as the CI relies on channels in some places. And again, I don't think spending time to adapt the CI there makes much sense, better rearrange it not to be a Luet centric project first, then it should not much impact if any at all. You already know how maddening it can be the toolkit CI sweat_smile

Haha, fair enough! :sweat_smile:

2023-04-25 08:47 UTC, frelon commented on pkg/types/v1/image.go
> +	ExtractImage(imageRef, destination, platformRef string, local bool) error
Yep, the latest commit adds authentication and I also tried running a local registry and pulling from that, which also works.

2023-04-25 10:11 UTC, davidcassany requested changes
Looks good so far. However I am concerned about the platform vs arch change. We need to be backward compatible in that regard. The only non backward compatible changes we should consider are related to the channels usage.

I don't think we will ever consider a platform that is no linux, so I am wondering about keeping arch field instead of platform and code translators, we already have `ArchToGolangArch` and `GolangArchToArch` in utils. We could have something like that to translate arch to platfrom and vice versa. In we could simply use these methods to code a couple of new ones `PlatformToArch` and `ArchToPlatform`. I think this would be the easiest way to be backward compatible. What you think?

Beyond the arch vs platform change all looks good from my point of view, great job :+1:

2023-04-25 10:11 UTC, davidcassany commented on cmd/flags.go
> +func addPlatformFlags(cmd *cobra.Command) {
Shouldn't we add a conversion between to two and deprecate `arch`? Note this also affects the `manifest.yaml` and `config.yaml`.

2023-04-25 10:11 UTC, davidcassany commented on cmd/config/config_test.go
> +			flags.Set("platform", "linux/arm64")
wouldn't it be an option to always assume `linux/<arch>` and keep around the arch parameter? Probably this is easier than coding `arch` backward compatibility and intruducing the new platform parameter.

2023-04-25 10:11 UTC, davidcassany commented on cmd/config/config_test.go
> +				Expect(iso.BootloaderInRootFs).To(BeTrue())
I'd keep it as a docker image instead. So we ensure only the ` channel` is gone.

2023-04-25 10:11 UTC, davidcassany commented on tests/fixtures/config/manifest.yaml
> -    - channel:recovery/cos-img
I'd just change them from `channel:..` to `oci:...` or `dir:...`. So we still test `image`, `uefi` and `rootfs` parameters in config.

2023-04-25 10:11 UTC, davidcassany commented on pkg/constants/constants.go
> -
Also the `GetBuildDiskDefaultPackages` should be gone here.

2023-04-25 10:11 UTC, davidcassany commented on pkg/types/v1/config.go
> +	Platform                  string   `yaml:"platform,omitempty" mapstructure:"platform"`
We need a migration path from `Arch` to  `Platform`. Note this impacts the ` config.yaml` and `manifest.yaml`. Is there any reason to change `Arch` to `Platform`? I still wonder if shouldn't we simply translate arch to platform internally, after all I doubt we will ever consider anything else than `linux` as a platform.

2023-04-25 10:11 UTC, davidcassany commented on tests/fixtures/config/manifest.yaml
>  raw_disk:
this should be gone too I think, the raw_disk is the data structure associated with the `build-disk` command.

2023-04-25 16:32 UTC, davidcassany commented on pkg/types/v1/config.go
> +	PlatformStr               string    `yaml:"platform,omitempty" mapstructure:"platform"`
I am not sure I understand the presence of Arch, PlatformStr and Platform here 🤔 I wonder if this could be re-arranged to some extend by a using a `CustomtUnmarshal` as in `types/v1/common.go`  and directly map `platform` yaml or flags to a Platform struct and avoid having the PlatformStr here. Then in sanitize we could use `arch`  as `platform` if this was not defined. So once we completely remove `arch` parameter we are only left with the `Platform` in struct.

2023-04-26 09:00 UTC, frelon commented on pkg/types/v1/config.go
> +	PlatformStr               string    `yaml:"platform,omitempty" mapstructure:"platform"`
Yep, platformstr was superfluous, added custom unmarshalling to Platform in latest commit instead. :+1:

2023-04-26 10:07 UTC, davidcassany approved these changes
Looks good to me now :+1:  Good job

We should be try not to add new (unrelated) stuff on top of that until we have verified it in `Dev` CI. Once verified we should tag a new version, so we have a clean cut of the change.

2023-04-26 10:07 UTC, merged