Add upgrade command
rancher/elemental-cli pull request #59
Opened 2022-01-27 13:42 UTC by Itxaka

Signed-off-by: Itxaka <igarcia@suse.com>

2022-01-27 16:29 UTC, davidcassany approved these changes
LGMT :+1:, just some comments regarding the logic to be implemented

2022-01-27 16:29 UTC, davidcassany commented on cmd/upgrade.go
> +		cmd.SilenceErrors = true // Do not propagate errors down the line, we control them
I am fine with this, but it is not clear to me what it does. Which errors are we omitting?

2022-01-27 16:29 UTC, davidcassany commented on pkg/action/upgrade.go
> +	// prepare statedir, if booting from recovery mount it, else remount state RW
Why not simply mount statedir as `rw`? remount if already mounted or simply mount it if not mounted.

I'd say checking how I booted is not the best option as it could be recovery, passive, ISO, etc. I'd say better stick to find state label (mount or remount as needed) and apply the upgraded image in there.

2022-01-27 16:29 UTC, davidcassany commented on pkg/action/upgrade.go
> +	// prepare target (create img file,grow it to expected size,mkfs ext2, mount as loop on statedir/cos/transition.img
JFYI Elemental has already a method to create and format an image file given a size and a filesystem.

2022-01-27 16:29 UTC, davidcassany commented on pkg/action/upgrade.go
> +	// prepare statedir, create dir, mount recovery partition into statedir
why the recovery partition has to be mounted in statedir...? makes no sense, cos.sh has some mountpoint variables absolutely insane and abused.

I'd do the same as I suggested for the Active upgrade, find recovery partition (mount or remount as needed) and apply the recovery image in there. I am not even sure it is required to check if we are in recovery partition at this point in time.

2022-01-28 08:23 UTC, Itxaka commented on cmd/upgrade.go
> +		cmd.SilenceErrors = true // Do not propagate errors down the line, we control them
yeah the only thing this does is prevent cobra from spitting the error itself, so we avoid double error printing (one to log and one to os.stdout)

Its simple to do it ourselves and print errors on our log directly and avoid cobra doing anything.

2022-01-28 08:24 UTC, Itxaka commented on pkg/action/upgrade.go
> +	// prepare statedir, if booting from recovery mount it, else remount state RW
yeas, this will be streamlined in the next commits...I hope :D

2022-01-28 08:24 UTC, Itxaka commented on pkg/action/upgrade.go
> +	// prepare target (create img file,grow it to expected size,mkfs ext2, mount as loop on statedir/cos/transition.img
niiiiiiice

2022-01-28 08:26 UTC, Itxaka commented on pkg/action/upgrade.go
> +	// prepare statedir, create dir, mount recovery partition into statedir
I dont understand it either. I think it all has to do with all the vars as you mentione, cos.sh does heavy use of the same vars all around just overwriting them in different places, which makes everything confuse af.

I think there is a small diff in the path if we are on recovery or not, but was not able to understand it properly.

2022-01-28 08:28 UTC, Itxaka commented on pkg/action/upgrade.go
> +	// switch images:
I think this is not correct, I screwed up here, cause if we want to upgrade the recovery what does the active/passive images has to do with anything??? I need to have a look at this again

2022-01-28 08:39 UTC, davidcassany commented on pkg/action/upgrade.go
> +	// prepare statedir, create dir, mount recovery partition into statedir
> I think there is a small diff in the path if we are on recovery or not, but was not able to understand it properly.

Yes I also struggle to identify some of the cos.sh paths. Anyway, in these cases I'd try to make the functionality clear and obvious even if there small behavior changes in some corner cases. I think some behaviors of cos.sh could be simple accidents caused by code reuse in different contexts.

2022-01-28 08:41 UTC, Itxaka commented on pkg/action/upgrade.go
> +	// prepare statedir, create dir, mount recovery partition into statedir
yep yep, the reasoning of putting the cos.sh workflow here is to be clear what is doing and try to make it as simple as possible while reusing most of the paths in a clear way.

2022-01-28 08:49 UTC, davidcassany commented on pkg/action/upgrade.go
> +	// prepare statedir, create dir, mount recovery partition into statedir
I could not resist. because of stuff like this we should be careful copying cos.sh logic:
https://github.com/rancher-sandbox/cOS-toolkit/blob/2db1242a2bdb8907e65d027cc11bfbf802874c62/packages/installer/cos.sh#L1213-L1218

a global variable called `_STATEDIR` is set to a device (wasn't supposed to be a directory?) here while in many other parts of the code is set to the mountpoint of the device... 😅

2022-01-31 14:21 UTC, davidcassany commented on pkg/types/v1/config.go
> +	DirectoryUpgrade string // configured only via flag, no need to map it to any config
I don't understand that, wouldn't `yaml:"directory,omitempty" mapstructure:"directory"` do the same without having use `viper.BindPFlag` in command configuration?

2022-01-31 14:25 UTC, davidcassany commented on pkg/types/v1/config.go
> +	DirectoryUpgrade string // configured only via flag, no need to map it to any config
OH I think I understand now. You don't want to map it into a config file, it can only be accessible as flag, it has to be set at runtime.

2022-01-31 16:43 UTC, davidcassany reviewed
Looks good to me. I believe we can reuse a little more from installer though. Also constants of labels should not be used, this is configurable data, you should relay on RunConfig for that.

2022-01-31 16:43 UTC, davidcassany commented on pkg/action/upgrade.go
> +		statePart, err = utils.GetFullDeviceByLabel(u.Config.Runner, constants.RecoveryLabel, 5)
mmm we have to carefully think about this `constants.RecoveryLabel` usage, note this is configurable, the constant just represents the default. Using RECOVERY_LABEL to something different in `/etc/cos/config` would break it.

2022-01-31 16:43 UTC, davidcassany commented on pkg/action/upgrade.go
> +		statePart, err = utils.GetFullDeviceByLabel(u.Config.Runner, constants.StateLabel, 5)
The same as above. I'd say we could relay on RunConfig.Partitions for this.

2022-01-31 16:43 UTC, davidcassany commented on cmd/upgrade.go
> +		if viper.GetString("docker-image") != "" && viper.GetString("directory") != "" {
Consider it a nit: I'd move this logic to `RunConfig.DigestSetup()` method (or probably makes sense having `DigestInstallSetup` and  `DisgestUpgradeSetup`). Also if you run this DigestSetup method you will get the partitions list populated, it could be useful to check labels and probably other stuff.

2022-01-31 16:43 UTC, davidcassany commented on pkg/action/upgrade.go
> +	err = u.Config.Fs.MkdirAll(constants.UpgradeStateDir, os.ModeDir)
Here if you have the partitions list defined you could eventually use the `Elemental.MountPartition` method and `Elemental.Unmount`, it already creates the directories if missing and the Unmount is also reentrant.

2022-01-31 16:43 UTC, davidcassany commented on pkg/action/upgrade.go
> +		if utils.BootedFrom(u.Config.Runner, constants.ActiveLabel) {
This label is also configurable, so the constant should not be used here.

2022-02-01 08:32 UTC, Itxaka commented on pkg/action/upgrade.go
> +		statePart, err = utils.GetFullDeviceByLabel(u.Config.Runner, constants.RecoveryLabel, 5)
umm, arent those values overloaded from the config? This is how it works on cos.sh, it uses `$RECOVERY_LABEL` to do all actions (search for partitions mainly) and others to do the upgrade.

Isnt the /etc/cos/config set on install, so the partition labels wont be changed??

Im very confused right now, because I can see what you mean, but I dont understand if it would even be possible to break it that way.

2022-02-01 08:33 UTC, Itxaka commented on pkg/action/upgrade.go
> +		statePart, err = utils.GetFullDeviceByLabel(u.Config.Runner, constants.RecoveryLabel, 5)
ah no, this is using constants!! my bad!

2022-02-01 14:24 UTC, davidcassany requested changes
The only thing that prevents me from giving it an approval is that I can't see anywhere the `tune2fs` calls to rename labels of images. I am missing something or it is a mistake?

All other comments are improvements that can be done in a second round, just not to make this PR even bigger.

2022-02-01 14:24 UTC, davidcassany commented on pkg/action/upgrade.go
> +		transitionImg = fmt.Sprintf("%s/cOS/%s", upgradeStateDir, constants.TransitionSquashFile)
nit: I think we could use the `filepath.Join` for that, it has little sanity checks and probably some portability features we don't care.

2022-02-01 14:24 UTC, davidcassany commented on pkg/action/upgrade.go
> +	// if upgrading the recovery we mount the state in a different place as its already mounted RO, we need to remount it
Out of curiosity, have we tried to remount over the same mountpoint?

2022-02-01 14:24 UTC, davidcassany commented on pkg/action/upgrade.go
> +		err = u.Config.Fs.MkdirAll(upgradeStateDir, os.ModeDir)
Oh, I like this `os.ModeDir`:+1: we should use it in `Elemental`.

2022-02-01 14:24 UTC, davidcassany commented on pkg/action/upgrade.go
> +type UpgradeSource struct {
I'd merge this into the v1.Image struct, so this data is stored there. There we could change `RootTree` by a `Source` and include this data. Then the v1.Image struct could be used for nicely to run all operations operations on images (create fs img, copyfile, unpack docker, etc.)

This can be done in a followup PR though.

2022-02-01 14:24 UTC, davidcassany commented on pkg/action/upgrade.go
> +	u.Config.Logger.Infof(s, args...)
Nice :+1:

2022-02-01 14:24 UTC, davidcassany commented on pkg/action/upgrade.go
> +		RootTree:   upgradeSource.source, // if source is a dir it will copy from here, if it's a docker img it uses Config.DockerImg IN THAT ORDER!
See, we could have a nested struct including `Source` and `Type` instead of `RootTree` here. This would make the logic explicit  and we could easily think of a nice CopyImage method that could be reused in many places.

2022-02-01 14:24 UTC, davidcassany commented on pkg/action/upgrade.go
> +		defer ele.UnmountImage(&img)
note this swallows unmounting errors. I think we should consider those, there could be errors on unmounting and having some explicit failure for that I think it is really good for debugging. This can be done in a follow up though. The install action uses kind of a simple (but verbose) pattern for that.

2022-02-01 14:24 UTC, davidcassany commented on pkg/action/upgrade.go
> +			// backup current active.img to passive.img before overwriting the active.img
I don't see the tune2fs call anywhere... ? See CopyRecovery and CopyPassive from `Elemental`. I think you missed to update the filesystem labels.

2022-02-01 14:32 UTC, Itxaka commented on pkg/action/upgrade.go
> +	// if upgrading the recovery we mount the state in a different place as its already mounted RO, we need to remount it
yes, not possible as its "on use"

2022-02-01 14:33 UTC, Itxaka commented on pkg/action/upgrade.go
> +		transitionImg = fmt.Sprintf("%s/cOS/%s", upgradeStateDir, constants.TransitionSquashFile)
Good point, I just steer far away from anything that sounds like a filesystem, so I didnt even consider it :D

2022-02-01 14:34 UTC, Itxaka commented on pkg/action/upgrade.go
> +type UpgradeSource struct {
yes, I thougth about expanding but didnt want to cascade things around, i.e. that modification maybe breaking something else. Good to me to integrate it afterwards!

2022-02-01 14:37 UTC, Itxaka commented on pkg/action/upgrade.go
> +		defer ele.UnmountImage(&img)
to be fair, do we really care in the upgrade? I mean, the next step after upgrade should be a reboot in which this will be unmounted automatically no? Plus the transition img will be autoremoved after a reboot. Its more of a "lets leave things as they were" than a "hard cleanup because we dont want to pollute the system". The magic of read only FS :laughing:

2022-02-01 14:37 UTC, Itxaka commented on pkg/action/upgrade.go
> +			// backup current active.img to passive.img before overwriting the active.img
wtf, I totally did

2022-02-01 14:38 UTC, Itxaka commented on pkg/action/upgrade.go
> +			// backup current active.img to passive.img before overwriting the active.img
wait, isnt the CreateFileSystemImage doing that automatically??

2022-02-01 14:47 UTC, davidcassany commented on pkg/action/upgrade.go
> +			// backup current active.img to passive.img before overwriting the active.img
CreateFileSystemImage creates an image with the `COS_ACTIVE` label. But old active image which will be moved to Passive should change the label from `COS_ACTIVE` to `COS_PASSIVE`.

2022-02-01 14:52 UTC, davidcassany commented on pkg/action/upgrade.go
> +			destination := fmt.Sprintf("%s/cOS/%s", upgradeStateDir, constants.PassiveImgFile)
Here `constants.PassiveImgFile`, is file that will have a filesystem of `COS_ACTIVE` unless we relabel it. If we don't then active and passive images will use the same FS Label and passive partition will miserably fail to boot, as grub expects `COS_PASSIVE` on `/cOS/passive.img`

2022-02-01 14:52 UTC, Itxaka commented on pkg/action/upgrade.go
> +			destination := fmt.Sprintf("%s/cOS/%s", upgradeStateDir, constants.PassiveImgFile)
yep, found it! Thanks for the pointer, totally forgot about the backup of active to passive!

2022-02-01 14:53 UTC, Itxaka commented on pkg/action/upgrade.go
> +			destination := fmt.Sprintf("%s/cOS/%s", upgradeStateDir, constants.PassiveImgFile)
Actually that also brings another error into mind, as Im setting the img.Label to simply "active" or "recovery" instead of the proper labels!

2022-02-01 16:07 UTC, davidcassany commented on pkg/action/upgrade.go
> +				u.Debug("Error while labeling the passive image %s, command output: %s", out)
A bit unrelated to this, but since a while I am thinking of adding the logger into the runner implementation so we can eventually add a debug message for every single Runner.Run execution. This would produce quite a detailed debug output and we would not need messages like that. The only issue is having initiate the runner with a logger and the little refactor it implies 🤷🏽‍♂️ 
 
 What you think?

2022-02-01 16:10 UTC, davidcassany commented on pkg/action/upgrade.go
> +			out, err := u.Config.Runner.Run("tune2fs", "-L", u.Config.PassiveLabel, destination)
yeah! :+1:

2022-02-01 16:27 UTC, Itxaka commented on pkg/action/upgrade.go
> +				u.Debug("Error while labeling the passive image %s, command output: %s", out)
umm, that would be great and avoid this extra stuff, as usually on debug I rather value the output of the commands (and the commands run!)

2022-02-01 16:40 UTC, davidcassany commented on pkg/action/upgrade.go
> +		img.Label = u.Config.RecoveryLabel
This is not correct... sorry I just saw it now. This label is the recovery partition label, not the recovery image label... yes pretty confusing. It should have been `u.Config.SystemLabel`. See the logic in https://github.com/rancher-sandbox/elemental/blob/42f728f36145bc921ea6ce7d72b345ecce3e5383/pkg/elemental/elemental.go#L475-L491
When the recovery image is not squashfs it is formatted using the `RunConfig.SystemLabel` value.

2022-02-01 16:43 UTC, Itxaka commented on pkg/action/upgrade.go
> +		img.Label = u.Config.RecoveryLabel
that is indeed confusing...but yes, I can see that is the way on the cos.sh script as well....wtf

2022-02-01 16:44 UTC, davidcassany approved these changes
Looks good to me. Just this issue on the recovery image label for the non-squashfs path.

2022-02-01 18:24 UTC, Itxaka commented
Ay ay ay, real life doest not conform to the ideal world of tests...
Need ot rework the geDeviceByLabel due to marshall errors...

2022-02-02 08:41 UTC, Itxaka commented on cmd/upgrade.go
> +		if viper.GetString("docker-image") != "" && viper.GetString("directory") != "" {
This sounds good but! I really like having everything related to command X in the cmd file related to that command, like the silenceErrors stuff, that could also be moved somewhere, but for someone having a look at the cmd stuff, having all this in here makes more sense to me. Call it self contained command related stuff, but going to the config feels like an extra step to me and makes it potentially confusing to understand where things related to this command are done.

I dont mind either way, but rather keep it here.

2022-02-02 09:27 UTC, davidcassany commented on pkg/types/v1/config.go
> +	PLabel     string   `json:"PARTLABEL,omitempty"`
Could it be that this makes it configurable from a config file? Note that PLabel is not configurable and uses constant values. Also there is no partition labels on MBR disks... so I'd say you will have a clash there having all the partitions with the same value if you actually feed it from some sort of disk analisys tool.

In fact, in the installer I used `PLabel` as a way to name and find partitions because it is not configurable so it is set in Partitions struct as a constant even if it is ignored for MBR.

That brings me to the point if we actually need to read the disk partitions to upgrade. Can't we simply assume the partitions are present based on the elemental current config? I mean we read the config hence we know the partitions and labels that are expected to be there, I see no need to fetch them from the disk.

2022-02-02 09:37 UTC, Itxaka commented on pkg/types/v1/config.go
> +	PLabel     string   `json:"PARTLABEL,omitempty"`
> Could it be that this makes it configurable from a config file? Note that PLabel is not configurable and uses constant values. Also there is no partition labels on MBR disks... so I'd say you will have a clash there having all the partitions with the same value if you actually feed it from some sort of disk analisys tool.

mmmh, it should not, this is only a mapping so when you unmarshall a json into a Partition struct, it identifies the fields that correspond to this, i.e. the json key `PARTLABEL` matches the `Plabel` key and the value is unmarshalled into that field in the struct. If struct field names match the json key names, then they are unmarshalled directly into those values.


> That brings me to the point if we actually need to read the disk partitions to upgrade. Can't we simply assume the partitions are present based on the elemental current config? I mean we read the config hence we know the partitions and labels that are expected to be there, I see no need to fetch them from the disk.

To read the FS type I think. I could not get the FS type any other way, and IIRC we cant assume they are using the default FS type no? I mean... Maybe I could use "auto" everywhere?

also the paths of them? Like on a normal HDD you get sda{1....4} but what about an ssd? Or a NVMe drive? My local NVMe has /dev/nvme0n1p{1...4} which is quite different. On qemu/vbox we may get /dev/vda{1...4}, etc...

This way also makes sure that we are not just "trying" to have the defaults but actually getting the real device info from the running system, which makes it more foolproof for the future. If you get the FS/path directly from the system, there is no way that can fail...maybe :P

2022-02-02 09:39 UTC, Itxaka commented on pkg/types/v1/config.go
> +	PLabel     string   `json:"PARTLABEL,omitempty"`
also the `Plabel` is actually not necessary as far as I can see(currently), so I could drop it. I thought that it would be good to have as much info as possible in the resulting `v1.Partition` in order to maybe reuse that method in the future when we need info from the running system partitions.

2022-02-02 10:09 UTC, davidcassany commented on pkg/types/v1/config.go
> +	PLabel     string   `json:"PARTLABEL,omitempty"`
Right, I see your point. The original idea is that the partitions should configurable in the future, meaning the partition struct could be eventually initiated from a yaml config file as part of the elemental configuration. So, I am not sure how can we match both. 

Regarding the PLabel if we fetch it from a tool then we need to name the partitions in an additional parameter.  At a time I did not do that as having Label, PLabel and Name I thought it was too much and even confusing. Probably we can consider renaming `PLabel` to `Name` and just use the `Name` as the partition label in partitioner as a convention, so I'd leave PLabel out of the disk analysis for now.

2022-02-02 10:16 UTC, Itxaka commented on pkg/types/v1/config.go
> +	PLabel     string   `json:"PARTLABEL,omitempty"`
well, this is only for json unmarshall, so has nothing to do with yaml unmarshall. I know, confusing as fuck. Im not sure what golang has against simple unmarshalling from yaml/json...

I will drop the plabel!

2022-02-02 19:07 UTC, Itxaka commented
Upgrades correctly.

But system running the upgrade (i.e. live system) gets corrupted, some binaries end up broken, cant restart. Force resetting boots the upgraded system correctly so it is upgrading as expected.

Grub is also not updated somehow.

So something is missing. Im rechecking the whole thing. I think that it may be due to copying over the active.img file with the transition.img, which leads to corruption in the current system? But that is the same as its done with the old installer so not sure why.

No more ideas to be honest. Unless I set a broken path somewhere and its mounting parts of the current FS somehow, I dont understand what is going on. AFAIK the active.img is mounted as a loop on /dev/loop0 which is mounted RO at /
If there is corruption due to copying the transition.img over the active.img...it should also occur with the normal script...

Im really puzzled. @davidcassany @mudler

2022-02-02 19:55 UTC, Itxaka commented
well, checking in older versions of the installer, when its was separated, the workflow seems a bit different....

https://github.com/rancher-sandbox/cOS-toolkit/blob/c8d6ad5f7f7f9e3eb9d3e552982e0ce507ef6fef/packages/installer/upgrade.sh#L12
```
# 1. Identify active/passive partition
# 2. Install upgrade in passive partition
# 3. Invert partition labels
```

2022-02-02 20:48 UTC, Itxaka commented
cant believe this shit.

So yeah old script was taking advantage of using `mv` as lostup shows, you can freely move the img file mounted and it will update it no problem. But of course that doesnt work if we copy using golang, we just override shit.


```
cos:/run/initramfs/cos-state/cOS # losetup
NAME       SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE                               DIO LOG-SEC
/dev/loop0         0      0         0  1 /run/initramfs/cos-state/cOS/active.img   0     512
cos:/run/initramfs/cos-state/cOS # mv active.img passive.img 
cos:/run/initramfs/cos-state/cOS # losetup
NAME       SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE                                DIO LOG-SEC
/dev/loop0         0      0         0  1 /run/initramfs/cos-state/cOS/passive.img   0     512
```

2022-02-03 15:02 UTC, davidcassany approved these changes
Looks good to me

2022-02-03 15:02 UTC, davidcassany commented on pkg/constants/constants.go
> +func GetDefaultSquashfsOptions() []string {
Nice!

2022-02-03 15:02 UTC, davidcassany commented on pkg/types/v1/config.go
> +	if r.ImgSize == 0 {
Today I was thinking if it would make sense to add a config test for default values, it feels quite stupid, but this kind of details are easy to forget. We could also define defaults with viper.SetDefault but I am not sure how to use it and if there is much gain. Ideally, would be nice to code the default as part of the struct `yaml` decorators but I could not find documentation about it 🤷🏽‍♂️

2022-02-03 15:02 UTC, davidcassany commented on pkg/utils/common.go
> +// TODO: Check validity of source maybe?
I don't think so, I would assume these kind of methods must get sanitized values. If not it should be a bug somewhere else.

2022-02-03 15:02 UTC, davidcassany commented on pkg/action/upgrade.go
> +	if chroot { // TODO: This is not really doing anything for hooks as it closes the chroot before running the hooks?
It sets the chroot here and it is closed right before returning upgradeHook method. The `utils.RunStage(hook, u.Config)` call will run in the chroot env if this is set to true.

2022-02-03 15:02 UTC, davidcassany commented on pkg/action/upgrade.go
> +	// Sorry, but I dont want to see all the yip stuff
Yes, yip messages tend to be quite annoying here.

2022-02-03 15:05 UTC, Itxaka commented on pkg/action/upgrade.go
> +	if chroot { // TODO: This is not really doing anything for hooks as it closes the chroot before running the hooks?
sure about that? 'Cause I was testing this and it wasnt running on the chroot as the actual chdir+chroot only happens *inside* the Run function :=)

2022-02-03 17:50 UTC, Itxaka commented on pkg/types/v1/config.go
> +	if r.ImgSize == 0 {
Yes, agree. We should probably have at least checks for non-empty values for things that should always be there. I.E. ImgSize is necessary but the running system may not have it, etc...

Take into account that Viper.Setdefaults is only for CMD commands, while this struct can be used from anywhere. So while I would like to also have checks and defaults in there, I think having them in this struct is much more important, as it can be used from other parts of our code not related to CMD

2022-02-03 17:51 UTC, Itxaka commented on pkg/utils/common.go
> +// TODO: Check validity of source maybe?
ummm, "assume" is the keyword here. If you pass a non existing value you would get a panic in runtime right? Not good. Maybe Im just used to code defensively due to python :D

2022-02-03 17:52 UTC, Itxaka commented on pkg/action/upgrade.go
> +	// Sorry, but I dont want to see all the yip stuff
yes, I think we should silence all by default and have a global flag in elemental to show cloud-init messages.

2022-02-03 17:53 UTC, merged

2022-02-04 08:50 UTC, davidcassany commented on pkg/action/upgrade.go
> +	if chroot { // TODO: This is not really doing anything for hooks as it closes the chroot before running the hooks?
gonna re-check it, I think I did a time but I could be wrong...