Do not use cosign luet plugin
rancher/elemental-cli pull request #65
Opened 2022-01-31 16:10 UTC by davidcassany

This commit instead of using luet's cosign plugin it just calls
cosign utility as needed. It facilitates a better use of environmental
variables and cosign specific flags.

Signed-off-by: David Cassany <dcassany@suse.com>

2022-01-31 16:13 UTC, davidcassany commented
Note this is only removing the use of luet-cosign plugin. For luet mtree plugin I believe calling it within luet makes complete sense as there is some luet specific logic around luet repositories to fetch metadata and so on.

2022-01-31 17:08 UTC, Itxaka commented on cmd/install.go
> +	installCmd.Flags().BoolP("cosign-key", "", false, "Sets the URL of the public key to be used by cosign validation")
Bool? Is this correct?

2022-01-31 17:10 UTC, davidcassany commented on cmd/install.go
> +	installCmd.Flags().BoolP("cosign-key", "", false, "Sets the URL of the public key to be used by cosign validation")
Ouch... 😓 This is certainly not correct

2022-02-01 08:49 UTC, davidcassany commented
I have few dubts from UI perspective. The client, with this PR, supports `--cosign` and `--cosign-key` falgs. If only `--cosign` is used it runs a keyless validation. For a validation using a public key it requires `--cosign --cosign-key=<key>`. I am wondering if it would make more sense something like `--cosign=<key>` to use cosign with public key and `--cosign` for keyless validation, so just reuse the same flag.

I think this could be cleaner from a user POV, what you think?

2022-02-01 12:13 UTC, davidcassany commented
> I am wondering if it would make more sense something like `--cosign=<key>` to use cosign with public key and `--cosign` for keyless validation, so just reuse the same flag.

Ok this is not possible in Cobra. So I am leaving it as is. For the time being.

2022-02-01 12:45 UTC, Itxaka requested changes

2022-02-01 12:45 UTC, Itxaka commented on cmd/install.go
> +	installCmd.Flags().StringP("cosign-key", "", "", "Sets the URL of the public key to be used by cosign validation")
I wonder if there is a way to link flags to subflags or something like that so we can group them.

2022-02-01 12:45 UTC, Itxaka commented on cmd/install.go
> +	installCmd.Flags().StringP("cosign-key", "", "", "Sets the URL of the public key to be used by cosign validation")
also URL OR file.

2022-02-01 12:45 UTC, Itxaka commented on pkg/utils/common.go
> +	}
sorry, we need to set the keyless verification which is only possible via....env var :D https://github.com/sigstore/cosign/blob/main/KEYLESS.md

So ...

```
if publicKey != "" {
	args = append(args, "-key", publicKey)
} else {
	os.Setenv("COSIGN_EXPERIMENTAL", 1)
}
```

2022-02-01 12:46 UTC, Itxaka reviewed
The idea would alos be to integrate the cosign stuff into the "new" config, so we only need to read from there instead of having to pass all the arguments.

Cant be done separately thought.

2022-02-01 12:48 UTC, Itxaka commented
> Ok this is not possible in Cobra. So I am leaving it as is. For the time being.

Probably doable by creating our own flag type I guess.

2022-02-01 12:56 UTC, davidcassany commented
> > Ok this is not possible in Cobra. So I am leaving it as is. For the time being.
> 
> Probably doable by creating our own flag type I guess.

The only option that I thought about is setting a known default something like `_none_` so if `RunConfig.Cosign` is set to `_none_` we can assume `--cosign` flag is not used. Then to set an empty key something like `elemental install --cosign= /dev/sda` must be used (not the `=` sign). So that I thought about keeping both flags separated as it the code for that is clear and obvious with the only downside of having to use two flags in order to make use of cosign, good thing is that `cosign: true` can be set in a config file, then the user just needs to use `--cosing-key`.

2022-02-01 12:56 UTC, davidcassany commented on pkg/utils/common.go
> +	}
Ouch damn it. Another round is coming

2022-02-01 13:03 UTC, Itxaka approved these changes

2022-02-01 13:07 UTC, merged