Add local flag to unpack local image
rancher/elemental-cli pull request #78
Opened 2022-02-04 11:30 UTC by Ludea

Add local flag to unpack local image instead of pulling it

2022-02-04 11:35 UTC, davidcassany commented on cmd/pull-image.go
> +        pullImage.Flags().Bool("local", false, "Use local imagz")
I guess this is a typo

2022-02-04 11:36 UTC, davidcassany commented on pkg/types/v1/luet.go
> +func (l Luet) Unpack(target string, image string, local bool) error {
Shouldn't `local`be used to run a local unpack of the image?

2022-02-04 11:39 UTC, davidcassany reviewed
@Ludea thanks much for your contribution, this is appreciated!

A couple of comments:
* Is the PR completed? To me it looks like it misses the actual local unpack from Luet API
* I am wondering if it the extra `--local` flag is needed, probably we can do something like try to state the given image as it was a local path and if it fails atempt to pull a registry.

2022-02-04 11:39 UTC, Ludea commented on cmd/pull-image.go
> +        pullImage.Flags().Bool("local", false, "Use local imagz")
Yes

2022-02-04 11:52 UTC, Ludea commented
> * Is the PR completed? To me it looks like it misses the actual local unpack from Luet API

Yes, you're right, I miss https://github.com/Ludea/elemental/blob/main/pkg/types/v1/luet.go#L56

> * I am wondering if it the extra `--local` flag is needed, probably we can do something like try to state the given image as it was a local path and if it fails atempt to pull from a registry.

It's an another way to do job. 
There is already an api with luet, with flag local, so we can use it. 
As you want

2022-02-04 12:32 UTC, Ludea commented
Implemented Luet api !

2022-02-04 13:06 UTC, Itxaka commented
Looks good to me. Its missing a test to see if the local path is run properly thought.

AFAIK this means that ti doesn't go to any remote but tries to get the image from the local docker daemon right? That is really helpful :D

2022-02-04 13:12 UTC, Ludea commented
> AFAIK this means that ti doesn't go to any remote but tries to get the image from the local docker daemon right? That is really helpful :D

Exactly 😊

2022-02-07 09:07 UTC, Itxaka commented on pkg/types/v1/luet_test.go
> +                        img, err := remote.Image(ref, remote.WithAuth(staticAuth{auth}))
`staticAuth` is not defined anywhere

2022-02-07 09:13 UTC, Itxaka commented on pkg/types/v1/luet_test.go
> +                        img, err := remote.Image(ref, remote.WithAuth(staticAuth{auth}))
```suggestion
			basicAuth := authn.Basic{}
                        img, err := remote.Image(ref, remote.WithAuth(&basicAuth)) 
```

2022-02-07 09:13 UTC, Itxaka commented on pkg/types/v1/luet_test.go
> +                        img, err := remote.Image(ref, remote.WithAuth(staticAuth{auth}))
This would require to `import 	"github.com/google/go-containerregistry/pkg/authn"`

2022-02-07 09:16 UTC, Itxaka commented
Im wondering if we could reuse the already used `docker` dependency for the test. Like we only need to pull an image into the local docker registry in order to test this, so bringing an extra dep into this seems overboard.

2022-02-07 09:37 UTC, Itxaka commented on pkg/types/v1/luet_test.go
> +                        img, err := remote.Image(ref, remote.WithAuth(staticAuth{auth}))
disregard this, I got it working with existing deps, so no need to import those new dependencies

2022-02-07 10:13 UTC, Itxaka requested changes
elemental bin was mistakenly added :D

2022-02-07 10:13 UTC, Itxaka commented on go.mod
> +	github.com/google/go-containerregistry v0.7.0
this can be dropped as its not needed anymore! Im guessing running `go mod tidy` should auto remove it?

2022-02-07 10:20 UTC, Itxaka commented on pkg/types/v1/luet_test.go
>  	. "github.com/onsi/ginkgo/v2"
missing importing `"context"` here

2022-02-08 06:36 UTC, closed without merging